project:
  type: book
  output-dir: docs

book:
  title: "商务智能"
  subtitle: "理论与Python实践"
  author: "商务智能课程"
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - part: "数据分析案例"
      chapters:
        - 泰坦尼克生存预测.qmd
        - 房价预测分析.qmd
  downloads: [pdf, epub]
  
format:
  html:
    theme: cosmo
    code-copy: true
    code-tools: true
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{ctex}
    
lang: zh

execute:
  echo: true
  warning: false 